---
title: 'Class 12: Web Scraping + Structured Text Extraction'
author: "Fadel M Megahed"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Continuing with the Plane Crash Info Example

```{r crashes}
year = 2025

crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')

crash_page <- rvest::read_html(crash_url, encoding = "ISO-8859-1")

# This should now print without the error
crash_page

# How many <table> elements are on the page?
crash_tables <- crash_page |>
  rvest::html_elements("table") |>
  rvest::html_table()

crash_tables

```



## ISA 125 Extraction

```{r isa125}
chat = ellmer::chat_openai(
  model = "gpt-5.6-luna"
)

isa125_courseblock = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/") |> 
  rvest::html_elements("#sc_sccoursedescs > div:nth-child(1)") |> 
  rvest::html_text2()

chat$chat_structured(
  isa125_courseblock,
  type = ellmer::type_object(
    # code is the name of the first element in the returned sublist
    # type_string -> forces that element to be of type chr
    code = ellmer::type_string(
      description = "The three letter abbreviation for the course and its number. For example, ISA 999 or FIN 444"
    ),
    name = ellmer::type_string(
      description = "The title of the course without the three letter abbreviation and the number. For example, Introduction to Macroeconomics. Do not return a period after the name"
    ),
    cr_hr = ellmer::type_integer(description = "The number of credits shown in parantheses after the course code and title")
  )
)
```


## All 50 ISA Courses

```{r all_isa_courses}
chat = ellmer::chat_openai(
  model = "gpt-5.6-luna"
)

course_vec = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/") |> 
  rvest::html_elements(".courseblock") |> rvest::html_text2()

# similar to http://ellmer.tidyverse.org/articles/structured-data.html
course_list = as.list(course_vec) # make it a list

# Fadel was lazy here and copied the schema from the prior example
# we did it for one class and now we apply it to all 50
type_course = ellmer::type_object(
    # code is the name of the first element in the returned sublist
    # type_string -> forces that element to be of type chr
    code = ellmer::type_string(
      description = "The three letter abbreviation for the course and its number. For example, ISA 999 or FIN 444"
    ),
    name = ellmer::type_string(
      description = "The title of the course without the three letter abbreviation and the number. For example, Introduction to Macroeconomics. Do not return a period after the name"
    ),
    cr_hr = ellmer::type_integer(description = "The number of credits shown in parantheses after the course code and title")
  )

isa_df = ellmer::parallel_chat_structured(
  chat = chat, prompts = course_list, type = type_course,
  include_tokens = T, include_cost = T
)

sum(isa_df$cost)
```



